export const characters: Character[] = [
  {
    name: 'J.',
    surname: 'Cortes',
    hintsA1: [],
    hintsA2: [],
    hintsA3: [],
    hintsA4: [],
    hintsA5: [],
  },
  {
    name: 'Lucia',
    surname: 'Cortes',
    hintsA1: [],
    hintsA2: [],
    hintsA3: [],
    hintsA4: [],
    hintsA5: [],
  },
  {
    name: 'Sergi',
    surname: 'Roca',
    hintsA1: [],
    hintsA2: [],
    hintsA3: [],
    hintsA4: [],
    hintsA5: [],
  },
  {
    name: 'Pedro',
    surname: 'Ferrer',
    hintsA1: [],
    hintsA2: [],
    hintsA3: [],
    hintsA4: [],
    hintsA5: [],
  },
  {
    name: 'Ernesto',
    surname: 'Larrea',
    hintsA1: [],
    hintsA2: [],
    hintsA3: [],
    hintsA4: [],
    hintsA5: [],
  },
  {
    surname: 'Garcia',
    title: 'Sargento',
    hintsA1: [],
    hintsA2: [],
    hintsA3: [],
    hintsA4: [],
    hintsA5: [],
  },
  {
    name: 'Marta',
    surname: 'Moreno',
    hintsA1: [],
    hintsA2: [],
    hintsA3: [],
    hintsA4: [],
    hintsA5: [],
  },
  {
    name: 'Abril',
    surname: 'Curto',
    hintsA1: [],
    hintsA2: [],
    hintsA3: [],
    hintsA4: [],
    hintsA5: [],
  },
  {
    name: 'Daniel',
    surname: 'Gutierrez',
    hintsA1: [],
    hintsA2: [],
    hintsA3: [],
    hintsA4: [],
    hintsA5: [],
  },
  {
    name: 'Andrea',
    surname: 'Marino',
    hintsA1: [],
    hintsA2: [],
    hintsA3: [],
    hintsA4: [],
    hintsA5: [],
  },
  {
    name: 'Ivette',
    surname: 'Ferrer',
    hintsA1: [],
    hintsA2: [],
    hintsA3: [],
    hintsA4: [],
    hintsA5: [],
  },
  {
    name: 'Carim',
    surname: 'Alam',
    hintsA1: [],
    hintsA2: [],
    hintsA3: [],
    hintsA4: [],
    hintsA5: [],
  },
  {
    name: 'Ema',
    surname: 'Dupont',
    hintsA1: [],
    hintsA2: [],
    hintsA3: [],
    hintsA4: [],
    hintsA5: [],
  }
]